# -*- coding: utf-8 -*-
"""forecast_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17MSezgRpQ1vMvOm8hqDOzahbrUPCfZp7
"""

import numpy as np
from tensorflow.keras.models import load_model
from sklearn.preprocessing import MinMaxScaler
import pickle  # যদি scaler সেভ করা থাকে

# Install Streamlit if it's not already installed and import it
try:
    import streamlit as st
except ImportError:
   
    import streamlit as st # Re-import after successful installation

st.title("Dhaka AQI Forecaster (LSTM Model)")
st.write("ঢাকার আগামী AQI প্রেডিক্ট করুন")

# ইউজার ইনপুট
temp = st.number_input("Expected Average Temperature (°C)", 10.0, 40.0, 28.0)
rain = st.number_input("Expected Rainfall (mm)", 0.0, 100.0, 0.0)

# ডামি ফিচার (তোমার মডেলের ইনপুট শেপ অনুযায়ী বদলাও)
# ধরে নিচ্ছি তোমার মডেল ৭ টাইমস্টেপ + ৬ ফিচার নেয়
dummy_features = np.array([[temp, rain, 0, 0, 0, 0]] * 7)  # 7 timesteps × features
dummy_features = dummy_features.reshape(1, 7, dummy_features.shape[1])

if st.button("Predict AQI"):
    try:
        # মডেল লোড করো
    model = load_model('dhaka_aqi_lstm_fixed.keras')

        # প্রেডিক্ট করো
        pred_scaled = model.predict(dummy_features, verbose=0)[0][0]

        # স্কেল ব্যাক (তোমার ট্রেইনিং-এর মিন-ম্যাক্স ব্যবহার করো)
        # এখানে ডামি স্কেলিং — আসল মিন/ম্যাক্স দিয়ে বদলাও
        pred_aqi = pred_scaled * 350 + 30

        st.success(f"**প্রেডিক্টেড AQI: {int(pred_aqi)}**")

        if pred_aqi > 150:
            st.warning("**স্বাস্থ্য পরামর্শ**: বাইরে N95 মাস্ক পরুন, শারীরিক পরিশ্রম কমান, সংবেদনশীল মানুষ ঘরে থাকুন।")
        elif pred_aqi > 100:
            st.info("**মাঝারি দূষণ** — সংবেদনশীল হলে বাইরের সময় কমান।")
        else:
            st.success("**ভালো বায়ুর গুণগত মান** — বাইরে যাওয়া নিরাপদ!")

    except Exception as e:
        st.error(f"সমস্যা: {str(e)}\nমডেল ফাইল 'dhaka_aqi_lstm.h5' আছে কি না চেক করুন।")
